name:                timezone-detect 
version:             0.1.0.2
github:              "lfborjas/timezone-detect"
license:             GPL-2
author:              "Luis Borjas Reyes"
maintainer:          "timezone-detect@lfborjas.com"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Haskell bindings for the zone-detect C library
category:            Data, Foreign 

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lfborjas/timezone-detect#readme>

dependencies:
- base >= 4.7 && < 4.14

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  c-sources:
    - csrc/zonedetect.c
  include-dirs: csrc
  install-includes:
    - csrc/zonedetect.h

tests:
  timezone-detect-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - timezone-detect
    - hspec >= 2.7 && < 2.8
    - directory >= 1.3 && < 1.4
    build-tools:
    - hspec-discover >= 2.7 && < 2.8
